export const keyNotes = {
  q: {
    order: 'c',
    color: 'white',
    duration: '5n',
    soundNote: 'C4',
    position: 1,
  },
  2: {
    order: 'cs',
    color: 'black',
    duration: '5n',
    soundNote: 'Cs4',
    position: 2,
  },
  w: {
    order: 'd',
    color: 'white',
    duration: '5n',
    soundNote: 'D4',
    position: 3,
  },
  3: {
    order: 'ds',
    color: 'black',
    duration: '5n',
    soundNote: 'Ds4',
    position: 4,
  },
  e: {
    order: 'e',
    color: 'white',
    duration: '5n',
    soundNote: 'E4',
    position: 5,
  },
  r: {
    order: 'f',
    color: 'white',
    duration: '5n',
    soundNote: 'F4',
    position: 6,
  },
  5: {
    order: 'fs',
    color: 'black',
    duration: '5n',
    soundNote: 'Fs4',
    position: 7,
  },
  t: {
    order: 'g',
    color: 'white',
    duration: '5n',
    soundNote: 'G4',
    position: 8,
  },
  6: {
    order: 'gs',
    color: 'black',
    duration: '5n',
    soundNote: 'Gs4',
    position: 9,
  },
  y: {
    order: 'a',
    color: 'white',
    duration: '5n',
    soundNote: 'A4',
    position: 10,
  },
  7: {
    order: 'as',
    color: 'black',
    duration: '5n',
    soundNote: 'As4',
    position: 11,
  },
  u: {
    order: 'b',
    color: 'white',
    duration: '5n',
    soundNote: 'B4',
    position: 12,
  },
  i: {
    order: 'c',
    color: 'white',
    duration: '5n',
    soundNote: 'C5',
    position: 13,
  },
  9: {
    order: 'cs',
    color: 'black',
    duration: '5n',
    soundNote: 'Cs5',
    position: 14,
  },
  o: {
    order: 'd',
    color: 'white',
    duration: '5n',
    soundNote: 'D5',
    position: 15,
  },
  0: {
    order: 'ds',
    color: 'black',
    duration: '5n',
    soundNote: 'Ds5',
    position: 16,
  },
  p: {
    order: 'e',
    color: 'white',
    duration: '5n',
    soundNote: 'E5',
    position: 17,
  },
  z: {
    order: 'f',
    color: 'white',
    duration: '5n',
    soundNote: 'F5',
    position: 18,
  },
  s: {
    order: 'fs',
    color: 'black',
    duration: '5n',
    soundNote: 'Fs5',
    position: 20,
  },
  x: {
    order: 'g',
    color: 'white',
    duration: '5n',
    soundNote: 'G5',
    position: 21,
  },
  d: {
    order: 'gs',
    color: 'black',
    duration: '5n',
    soundNote: 'Gs5',
    position: 22,
  },
  c: {
    order: 'a',
    color: 'white',
    duration: '5n',
    soundNote: 'A5',
    position: 23,
  },
  f: {
    order: 'as',
    color: 'black',
    duration: '5n',
    soundNote: 'As5',
    position: 24,
  },
  v: {
    order: 'b',
    color: 'white',
    duration: '5n',
    soundNote: 'B5',
    position: 25,
  },
  b: {
    order: 'c',
    color: 'white',
    duration: '5n',
    soundNote: 'C6',
    position: 26,
  },
  h: {
    order: 'cs',
    color: 'black',
    duration: '5n',
    soundNote: 'Cs6',
    position: 27,
  },
  n: {
    order: 'd',
    color: 'white',
    duration: '5n',
    soundNote: 'D6',
    position: 28,
  },
  j: {
    order: 'ds',
    color: 'black',
    duration: '5n',
    soundNote: 'Ds6',
    position: 29,
  },
  m: {
    order: 'e',
    color: 'white',
    duration: '5n',
    soundNote: 'E6',
    position: 30,
  },
  ",": {
    order: 'f',
    color: 'white',
    duration: '5n',
    soundNote: 'F6',
    position: 31,
  },
  "l": {
    order: 'fs',
    color: 'black',
    duration: '5n',
    soundNote: 'Fs6',
    position: 32,
  },
  ".": {
    order: 'g',
    color: 'white',
    duration: '5n',
    soundNote: 'G6',
    position: 33,
  },
  ";": {
    order: 'gs',
    color: 'black',
    duration: '5n',
    soundNote: 'Gs6',
    position: 34,
  },
  "/": {
    order: 'a',
    color: 'white',
    duration: '5n',
    soundNote: 'A6',
    position: 35,
  },
};
