export const The_scientist = {
  name: 'The Scientist',
  artist: 'Coldplay',
  song: {
    bpm: 0.45,
    piano: [
      { note: 'D4', duration: '4n', noteDelayIndex: 0 },
      { note: 'C5', duration: '4n', noteDelayIndex: 0 },
      { note: 'D5', duration: '4n', noteDelayIndex: 0 },
      { note: 'F5', duration: '4n', noteDelayIndex: 0 },
      { note: 'A5', duration: '4n', noteDelayIndex: 0 },
      { note: 'D4', duration: '4n', noteDelayIndex: 1 },
      { note: 'C5', duration: '4n', noteDelayIndex: 2 },
      { note: 'D5', duration: '4n', noteDelayIndex: 2 },
      { note: 'F5', duration: '4n', noteDelayIndex: 2 },
      { note: 'A5', duration: '4n', noteDelayIndex: 2 },
      { note: 'D5', duration: '4n', noteDelayIndex: 2 },
      { note: 'D4', duration: '4n', noteDelayIndex: 2 },
      { note: 'D4', duration: '4n', noteDelayIndex: 3 },
      { note: 'D5', duration: '4n', noteDelayIndex: 4 },
      { note: 'C5', duration: '4n', noteDelayIndex: 4 },
      { note: 'D5', duration: '4n', noteDelayIndex: 4 },
      { note: 'F5', duration: '4n', noteDelayIndex: 4 },
      { note: 'A5', duration: '4n', noteDelayIndex: 4 },
      { note: 'D4', duration: '4n', noteDelayIndex: 4 },
      { note: 'D4', duration: '4n', noteDelayIndex: 5 },
      { note: 'D5', duration: '4n', noteDelayIndex: 6 },
      { note: 'C5', duration: '4n', noteDelayIndex: 6 },
      { note: 'D5', duration: '4n', noteDelayIndex: 6 },
      { note: 'F5', duration: '4n', noteDelayIndex: 6 },
      { note: 'A5', duration: '4n', noteDelayIndex: 6 },
      { note: 'D4', duration: '4n', noteDelayIndex: 6 },
      { note: 'D4', duration: '4n', noteDelayIndex: 7 },
      //main piano part 1
      { note: 'As5', duration: '4n', noteDelayIndex: 8 },
      { note: 'D5', duration: '4n', noteDelayIndex: 8 },
      { note: 'F5', duration: '4n', noteDelayIndex: 8 },
      { note: 'As4', duration: '4n', noteDelayIndex: 8 },
      { note: 'As4', duration: '4n', noteDelayIndex: 9 },
      { note: 'As5', duration: '4n', noteDelayIndex: 10 },
      { note: 'D5', duration: '4n', noteDelayIndex: 10 },
      { note: 'F5', duration: '4n', noteDelayIndex: 10 },
      { note: 'As4', duration: '4n', noteDelayIndex: 10 },
      { note: 'As4', duration: '4n', noteDelayIndex: 11 },
      { note: 'As5', duration: '4n', noteDelayIndex: 12 },
      { note: 'D5', duration: '4n', noteDelayIndex: 12 },
      { note: 'F5', duration: '4n', noteDelayIndex: 12 },
      { note: 'As4', duration: '4n', noteDelayIndex: 12 },
      { note: 'As4', duration: '4n', noteDelayIndex: 13 },
      { note: 'As5', duration: '4n', noteDelayIndex: 14 },
      { note: 'D5', duration: '4n', noteDelayIndex: 14 },
      { note: 'F5', duration: '4n', noteDelayIndex: 14 },
      { note: 'As4', duration: '4n', noteDelayIndex: 14 },
      { note: 'As4', duration: '4n', noteDelayIndex: 15 },
      { note: 'C5', duration: '4n', noteDelayIndex: 15 },
      { note: 'C6', duration: '4n', noteDelayIndex: 15 },
      //main piano part 2
      { note: 'F4', duration: '4n', noteDelayIndex: 16 },
      { note: 'C5', duration: '4n', noteDelayIndex: 16 },
      { note: 'F5', duration: '4n', noteDelayIndex: 16 },
      { note: 'A5', duration: '4n', noteDelayIndex: 16 },
      { note: 'F4', duration: '4n', noteDelayIndex: 17 },
      { note: 'F4', duration: '4n', noteDelayIndex: 18 },
      { note: 'C5', duration: '4n', noteDelayIndex: 18 },
      { note: 'F5', duration: '4n', noteDelayIndex: 18 },
      { note: 'A5', duration: '4n', noteDelayIndex: 18 },
      { note: 'F4', duration: '4n', noteDelayIndex: 19 },
      { note: 'F4', duration: '4n', noteDelayIndex: 20 },
      { note: 'C5', duration: '4n', noteDelayIndex: 20 },
      { note: 'F5', duration: '4n', noteDelayIndex: 20 },
      { note: 'A5', duration: '4n', noteDelayIndex: 20 },
      { note: 'F4', duration: '4n', noteDelayIndex: 21 },
      { note: 'F4', duration: '4n', noteDelayIndex: 22 },
      { note: 'C5', duration: '4n', noteDelayIndex: 22 },
      { note: 'F5', duration: '4n', noteDelayIndex: 22 },
      { note: 'A5', duration: '4n', noteDelayIndex: 22 },
      { note: 'F4', duration: '4n', noteDelayIndex: 23 },
      //main piano part 3
      { note: 'F4', duration: '4n', noteDelayIndex: 24 },
      { note: 'C5', duration: '4n', noteDelayIndex: 24 },
      { note: 'F5', duration: '4n', noteDelayIndex: 24 },
      { note: 'G5', duration: '4n', noteDelayIndex: 24 },
      { note: 'F4', duration: '4n', noteDelayIndex: 25 },
      { note: 'F4', duration: '4n', noteDelayIndex: 26 },
      { note: 'C5', duration: '4n', noteDelayIndex: 26 },
      { note: 'F5', duration: '4n', noteDelayIndex: 26 },
      { note: 'G5', duration: '4n', noteDelayIndex: 26 },
      { note: 'F4', duration: '4n', noteDelayIndex: 27 },
      { note: 'F4', duration: '4n', noteDelayIndex: 28 },
      { note: 'C5', duration: '4n', noteDelayIndex: 28 },
      { note: 'F5', duration: '4n', noteDelayIndex: 28 },
      { note: 'G5', duration: '4n', noteDelayIndex: 28 },
      { note: 'F4', duration: '4n', noteDelayIndex: 29 },
      { note: 'F4', duration: '4n', noteDelayIndex: 30 },
      { note: 'C5', duration: '4n', noteDelayIndex: 30 },
      { note: 'F5', duration: '4n', noteDelayIndex: 30 },
      { note: 'G5', duration: '4n', noteDelayIndex: 30 },
      { note: 'F4', duration: '4n', noteDelayIndex: 31 },
    ],
  },
};
